a = input ("Digite algo: ")
print ('O tipo primitivo desse valor è ', type(a))
print ('Só tem espaços?' , a.isspace())
print('è um número? ', a.isnumeric())
print('é alfabético?', a.isalpha())
print('é alfanumerico? ',a.isalnum())
print('é maiuscula? ', a.isupper())
print('è minuscula? ',a.islower())
print('está capitalizada? ',a.istitle())